### ISSUE TITLE
Azure_Storage_DP_Encrypt_In_Transit Failing unused property in Storage Account Blobservices ARM Template

### ISSUE THREAD

**Issue by andrewholler** [azsk/DevOpsKit#1089]
## Description</br>
When running Get-AzSKARMTemplateSecurityStatus on a storage account blobservices ARM template, the task will fail because it is evaluating the control, Azure_Storage_DP_Encrypt_In_Transit. This control should not be evaluated for blobservices because supportsHttpsTrafficOnly is not a supported property on blobservices as seen by the schema reference: https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2019-06-01/Microsoft.Storage.json

## Steps to reproduce

Azure DevOps Pipeline Task

```YAML
- task: AzSKARMTemplateChecker@4
  displayName: Validate Security Controls - $(printService)
  inputs:
    ARMTemplateFilePath: storage-account-blobservices.json
    ARMTemplateParameterFilePath: storage-account-blobservices.param.json
  continueOnError: true
```
## Expected behavior</br> 
Azure_Storage_DP_Encrypt_In_Transit should not get evaluated for blobservices because "supportsHttpsTrafficOnly" is not a valid property for the blobservices ARM template. You can see it is not a supported property in the blobServices ARM template schema here: https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2019-06-01/Microsoft.Storage.json

## Actual behavior</br>
ControlId | FeatureName | Status | SupportedResources | Severity | PropertyPath | LineNumber | CurrentValue | ExpectedProperty | ExpectedValue | ResourcePath | ResourceLineNumber | Description | FilePath
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Azure_Storage_DP_Encrypt_In_Transit | Storage | Failed | Microsoft.Storage/storageAccounts ,   Microsoft.Storage/storageAccounts/blobServices | High | Not found | -1 |   | $.properties.supportsHttpsTrafficOnly | 'True' | resources[0] | 33 | HTTPS protocol must be used for accessing Storage Account resources | D:\a\1\s\templates\storage-account\storage-account-blobservices.json
